### ISSUE TITLE
The download links for the pre-trained model are not available

### ISSUE THREAD

**Issue by zhijiew** [zbf1991/SCL#3]
Thank you for your great work!

I'm checking your codes recently, but I can't download the pre-trained model from your links, it looks like some permission issue, can you check it or use some other service?

Thanks!

![Xnip2021-06-30_12-27-15](https://user-images.githubusercontent.com/10759053/123897646-b8989680-d99e-11eb-8523-bce95f25d0db.png)

**Comment by zbf1991** [comment]
Sorry for that. The URL is now available.
