### ISSUE TITLE
Evaluation iteration for COCO in 5-shot setting.

### ISSUE THREAD

**Issue by zhijiew** [zbf1991/SCL#8]
Thank you for your great work!

You set the test_num=3000 (L175 in test_5shot.py) for COCO 5-shot scenario in PFENet, it is different with the original PFENet's setting and the 1-shot scenario, which is 20000. Should I use this setting (3000) or correct it (20000) for fair comparision with your method?

**Comment by zbf1991** [comment]
You can correct it to 20000 for a fair comparison.

**Comment by zhijiew** [comment]
Got it. Thanks!
