### ISSUE TITLE
how to generate SegmentationClassAug？

### ISSUE THREAD

**Issue by WHL182** [zbf1991/SCL#9]
I have downloaded the PASCAL VOC 2012 dataset and SBD dataset from their official website respectively.But I donnot know how to use them in the code .Could you show me your dataset folder structure or the method to generate SegmentationClassAug?

**Comment by zbf1991** [comment]
'SegmentationClassAug' can be downloaded from: https://www.dropbox.com/s/oeu149j8qtbs1x0/SegmentationClassAug.zip?dl=0

**Comment by WHL182** [comment]
Thank you！
